### PR TITLE
Adding new bindings to rdkit 

### PR DESCRIPTION
**Pull request by mvisani**
I've added a couple of additional bindings to the crate. They all include tests. 
@xrl I would argue that this pull request should be accepted after pull request #35

### CODE REVIEW

**Comment by xrl** [comment]
Can you do a quick `cargo fmt`?

**Comment by mvisani** [comment]
@xrl  Sorry for the late reply, all tests are passing now.

**Comment by mvisani** [comment]
@xrl I'm planning to work on adding other bindings. Would you prefer that each one has its own PR ? Should I continue on this one ?

**Review by xrl — APPROVED** [review]
This looks good, let's move further work to another PR

**Pull request merged**
