### PR TITLE
Add most common isotope mass function, getProp and setProp

### PR DESCRIPTION
**Pull request by mvisani**
Given a the chemical symbol of the atom, return the most common isotope mass of that atom.

### CODE REVIEW

**Comment by mvisani** [comment]
@xrl @JJ-Pineda the commits diverged a bit from the title of the pull request however I still made some advancements. Any chance I could get a review on those changes ? Or perhaps being added as a contributor to the project ?

**Comment by xrl** [comment]
I would prefer three PRs for this work, it is a little too large to review.

 1. adding the new bindings and associated tests
 2. renaming existing bindings
 3. reformatting the C++ with clang tooling (I had look at this and didn't tackle it, thank you!). also please adding the C++ format checks to github actions. I will approve CI runs for your PRs.

**Comment by mvisani** [comment]
@xrl Thanks for your reply ! Point 3 should be solved in pull request #35. I'll notify you when i'm done with the others.

**Comment by mvisani** [comment]
I will close this pull request as it has been split into smaller ones.

**Pull request closed without merging**
